version: "4.0"

services:
  dev:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
    user: root
    volumes:
      - ../..:/workspaces:z
    command: sleep infinity
    
  mongo: 
    image: mongo:7